/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScreeningIndexRouteImport } from './routes/screening/index'
import { Route as FundsIndexRouteImport } from './routes/funds/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as FundsCodeRouteImport } from './routes/funds/$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreeningIndexRoute = ScreeningIndexRouteImport.update({
  id: '/screening/',
  path: '/screening/',
  getParentRoute: () => rootRouteImport,
} as any)
const FundsIndexRoute = FundsIndexRouteImport.update({
  id: '/funds/',
  path: '/funds/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const FundsCodeRoute = FundsCodeRouteImport.update({
  id: '/funds/$code',
  path: '/funds/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/funds/$code': typeof FundsCodeRoute
  '/chat/': typeof ChatIndexRoute
  '/funds/': typeof FundsIndexRoute
  '/screening/': typeof ScreeningIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/funds/$code': typeof FundsCodeRoute
  '/chat': typeof ChatIndexRoute
  '/funds': typeof FundsIndexRoute
  '/screening': typeof ScreeningIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/funds/$code': typeof FundsCodeRoute
  '/chat/': typeof ChatIndexRoute
  '/funds/': typeof FundsIndexRoute
  '/screening/': typeof ScreeningIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/funds/$code' | '/chat/' | '/funds/' | '/screening/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/funds/$code' | '/chat' | '/funds' | '/screening'
  id: '__root__' | '/' | '/funds/$code' | '/chat/' | '/funds/' | '/screening/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FundsCodeRoute: typeof FundsCodeRoute
  ChatIndexRoute: typeof ChatIndexRoute
  FundsIndexRoute: typeof FundsIndexRoute
  ScreeningIndexRoute: typeof ScreeningIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screening/': {
      id: '/screening/'
      path: '/screening'
      fullPath: '/screening/'
      preLoaderRoute: typeof ScreeningIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funds/': {
      id: '/funds/'
      path: '/funds'
      fullPath: '/funds/'
      preLoaderRoute: typeof FundsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funds/$code': {
      id: '/funds/$code'
      path: '/funds/$code'
      fullPath: '/funds/$code'
      preLoaderRoute: typeof FundsCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FundsCodeRoute: FundsCodeRoute,
  ChatIndexRoute: ChatIndexRoute,
  FundsIndexRoute: FundsIndexRoute,
  ScreeningIndexRoute: ScreeningIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
